// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum Arcana {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Major = "major",
    Minor = "minor",
};

export interface Card {
    "id": string;
    "name": string;
    "arcana": Arcana;
    "number": number;

    /**
     * Для младших арканов:
     * wands, cups, swords, pentacles
     */
    "suit"?: string;
    "image": string;
    "keywords": string[] | null;
    "upright": CardMeaning;
    "reversed": CardMeaning;
}

export interface CardMeaning {
    "text": string;
    "love": string;
    "career": string;
    "finance": string;
    "health": string;
    "advice": string;
}

/**
 * DailyAnimation описание появления карты дня.
 */
export interface DailyAnimation {
    "card": DailyCard;
    "startX": number;
    "startY": number;
    "startScale": number;
    "x": number;
    "y": number;
    "scale": number;
    "rotation": number;
    "delay": number;
    "duration": number;
    "glow": boolean;
    "particles": boolean;
}

/**
 * DailyCard хранит карту дня.
 */
export interface DailyCard {
    /**
     * Дата получения
     */
    "date": string;

    /**
     * Выпавшая карта
     */
    "card": DrawnCard;

    /**
     * Текст для экрана
     */
    "message": string;
}

export interface DrawnCard {
    "card": Card;
    "isReversed": boolean;
    "quickAnswer"?: string;
    "historyId"?: number;
}

/**
 * GuideSection один раздел руководства (или справки о Таро).
 */
export interface GuideSection {
    "title": string;
    "text": string;
}

/**
 * HistoryRecord одна запись истории.
 */
export interface HistoryRecord {
    "id": number;
    "date": string;

    /**
     * spread / daily / single
     */
    "type": string;
    "name": string;
    "spreadId"?: string;
    "question": string;
    "comment"?: string;
    "cards": DrawnCard[] | null;
}

/**
 * LegalDocs оба юридических документа приложения.
 */
export interface LegalDocs {
    "privacy": LegalSection;
    "terms": LegalSection;
}

/**
 * LegalSection один текстовый документ (политика или условия).
 */
export interface LegalSection {
    "title": string;
    "paragraphs": string[] | null;
}

/**
 * QuestionCategory группа вопросов с подписью.
 */
export interface QuestionCategory {
    "id": string;
    "label": string;
    "questions": string[] | null;
}

export interface Spread {
    "id": string;
    "name": string;
    "description": string;

    /**
     * Размер области расклада для интерфейса
     */
    "width": number;
    "height": number;
    "positions": SpreadPosition[] | null;
}

/**
 * Карта в конкретной позиции.
 */
export interface SpreadCard {
    "position": SpreadPosition;
    "card": Card;
    "isReversed": boolean;
    "quickAnswer"?: string;
}

/**
 * Позиция карты в раскладе.
 */
export interface SpreadPosition {
    "index": number;

    /**
     * внутренний ключ позиции
     */
    "key": string;
    "name": string;
    "description": string;

    /**
     * координаты для frontend (%)
     */
    "x": number;
    "y": number;

    /**
     * угол поворота карты
     */
    "rotation": number;
}

/**
 * Результат гадания.
 */
export interface SpreadResult {
    "spread": Spread;
    "cards": SpreadCard[] | null;
    "quickAnswer"?: string;
    "historyId"?: number;
}
