// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TarotService — сервис, который Wails v3 забиндит на фронтенд.
 * Методы те же, что были у App в v2, но теперь это
 * application.Service, а не часть структуры с ctx.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tarot$0 from "./tarot/models.js";

export function ClearHistory(): $CancellablePromise<void> {
    return $Call.ByID(3467326442);
}

export function DeleteHistoryRecord(id: number): $CancellablePromise<void> {
    return $Call.ByID(2317102423, id);
}

export function DrawCard(): $CancellablePromise<tarot$0.DrawnCard | null> {
    return $Call.ByID(450147037);
}

export function DrawCards(count: number): $CancellablePromise<tarot$0.DrawnCard[] | null> {
    return $Call.ByID(3939846122, count);
}

export function DrawSpread(spreadID: string, question: string): $CancellablePromise<tarot$0.SpreadResult | null> {
    return $Call.ByID(3400679900, spreadID, question);
}

export function FullDeck(): $CancellablePromise<tarot$0.Card[] | null> {
    return $Call.ByID(2390154013);
}

export function GetAboutTarot(): $CancellablePromise<tarot$0.GuideSection[] | null> {
    return $Call.ByID(3472497208);
}

export function GetDailyAnimation(): $CancellablePromise<tarot$0.DailyAnimation | null> {
    return $Call.ByID(2565274946);
}

export function GetDailyCard(): $CancellablePromise<tarot$0.DailyCard | null> {
    return $Call.ByID(730404650);
}

export function GetGuide(): $CancellablePromise<tarot$0.GuideSection[] | null> {
    return $Call.ByID(603213405);
}

export function GetHistory(): $CancellablePromise<tarot$0.HistoryRecord[] | null> {
    return $Call.ByID(111576065);
}

export function GetLastHistory(count: number): $CancellablePromise<tarot$0.HistoryRecord[] | null> {
    return $Call.ByID(550731585, count);
}

export function GetLegal(): $CancellablePromise<tarot$0.LegalDocs | null> {
    return $Call.ByID(2414719180);
}

export function GetQuestions(): $CancellablePromise<tarot$0.QuestionCategory[] | null> {
    return $Call.ByID(2057804024);
}

export function GetSettings(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(913409074);
}

export function GetSpreads(): $CancellablePromise<tarot$0.Spread[] | null> {
    return $Call.ByID(683252537);
}

export function HistoryCount(): $CancellablePromise<number> {
    return $Call.ByID(1234369118);
}

export function LastSpread(): $CancellablePromise<tarot$0.Spread | null> {
    return $Call.ByID(3900020122);
}

export function RemainingCards(): $CancellablePromise<number> {
    return $Call.ByID(2211910234);
}

export function RemainingCardsList(): $CancellablePromise<tarot$0.Card[] | null> {
    return $Call.ByID(2956914742);
}

export function ResetDailyCard(): $CancellablePromise<void> {
    return $Call.ByID(302095755);
}

export function ResetDeck(): $CancellablePromise<string> {
    return $Call.ByID(336193185);
}

export function Shuffle(): $CancellablePromise<string> {
    return $Call.ByID(1466474422);
}

export function Status(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3612904711);
}

export function Today(): $CancellablePromise<string> {
    return $Call.ByID(3306210438);
}

export function UpdateHistoryComment(id: number, comment: string): $CancellablePromise<void> {
    return $Call.ByID(1476390841, id, comment);
}

export function UpdateSetting(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(4153506808, key, value);
}
